package com.example.mathsapi.linkedIn

data class LinkedIn(
    val awards: Awards,
    val background_image: String,
    val birth_date: Any,
    val certifications: Certifications,
    val contact_info: Any,
    val courses: Courses,
    val education: List<Education>,
    val entity_urn: String,
    val first_name: String,
    val industry: String,
    val influencer: Boolean,
    val info: String,
    val languages: Languages,
    val last_name: String,
    val location: Location,
    val network_info: Any,
    val object_urn: Int,
    val organizations: Organizations,
    val patents: Patents,
    val position_groups: List<PositionGroup>,
    val premium: Boolean,
    val profile_id: String,
    val profile_picture: String,
    val profile_type: String,
    val projects: Projects,
    val publications: Publications,
    val related_profiles: Any,
    val skills: Skills,
    val sub_title: String,
    val summary: String,
    val test_scores: TestScores,
    val treasury_media: TreasuryMedia,
    val volunteer_experiences: VolunteerExperiences
)